{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# -*- coding: utf-8 -*-\n",
    "\"\"\"\n",
    "General Information\n",
    "* Created by: \ud83e\udd8a Florent Poux. \n",
    "* Copyright: Florent Poux.\n",
    "* License: MIT\n",
    "* Status: Online\n",
    "\n",
    "Dependencies:\n",
    "* Anaconda or Miniconda\n",
    "* An Anaconda new environment\n",
    "* Libraries as described in the Chapter\n",
    "\n",
    "Have fun with this Code Solution.\n",
    "\n",
    "\ud83c\udfb5 Note: Styling was not taken care of at this stage.\n",
    "\n",
    "Enjoy!\n",
    "\"\"\"\n",
    "\n",
    "import cadquery as cq\n",
    "import open3d as o3d\n",
    "import numpy as np\n",
    "\n",
    "#%% 1. Basic Modelling Techniques\n",
    "\n",
    "# https://cadquery.readthedocs.io/en/latest/examples.html#plate-with-hole\n",
    "\n",
    "cube = cq.Workplane().box(1, 1, 1)\n",
    "\n",
    "# Show the cube\n",
    "cq.show(cube)\n",
    "\n",
    "#%% 1.1. Sketching (2D CAD)\n",
    "\n",
    "pts = [(0,0),(0,20),(12,20),(12,18),(2,18),(2,16),(8,16),(8,14),(2,14),(2,0)]\n",
    "\n",
    "flo = cq.Workplane(\"front\").polyline(pts).close()\n",
    "\n",
    "cq.exporters.export(flo, \"../RESULTS/letter.dxf\")\n",
    "\n",
    "# Example better\n",
    "\n",
    "(L, H, W, t) = (100.0, 20.0, 20.0, 1.0)\n",
    "pts = [\n",
    "    (0, H / 2.0),\n",
    "    (W / 2.0, H / 2.0),\n",
    "    (W / 2.0, (H / 2.0 - t)),\n",
    "    (t / 2.0, (H / 2.0 - t)),\n",
    "    (t / 2.0, (t - H / 2.0)),\n",
    "    (W / 2.0, (t - H / 2.0)),\n",
    "    (W / 2.0, H / -2.0),\n",
    "    (0, H / -2.0),\n",
    "]\n",
    "result = cq.Workplane(\"front\").polyline(pts).mirrorY().extrude(L)\n",
    "cq.exporters.export(result, \"../RESULTS/IPN.stl\")\n",
    "\n",
    "#%% 1.2. Extruding\n",
    "\n",
    "flo_e = cq.Workplane(\"front\").polyline(pts).close().extrude(1)\n",
    "cq.exporters.export(flo_e, \"../RESULTS/letter.stl\")\n",
    "\n",
    "#%% Visualize within Python"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def visualize_object(cq_object):\n",
    "    temp_path = \"../RESULTS/temp.stl\"\n",
    "    cq.exporters.export(cq_object, temp_path)\n",
    "    o3d_mesh = o3d.io.read_triangle_mesh(temp_path)\n",
    "    o3d_mesh.compute_vertex_normals()\n",
    "    o3d.visualization.draw_geometries([o3d_mesh])\n",
    "\n",
    "#%% Revolving\n",
    "\n",
    "# Define the profile\n",
    "profile = cq.Sketch()\n",
    "with profile:\n",
    "    profile.rect(1, 2).finalize()\n",
    "\n",
    "# Extrude the profile\n",
    "extruded = profile.extrude(2)\n",
    "\n",
    "# Revolve the extruded shape\n",
    "result = extruded.revolve(360)\n",
    "visualize_object(result)\n",
    "\n",
    "#%% 1.3 Fillet\n",
    "\n",
    "result = cq.Workplane(\"XY\").box(3, 3, 0.5)\n",
    "visualize_object(result)\n",
    "\n",
    "result = cq.Workplane(\"XY\").box(3, 3, 0.5).edges(\"|Z\").fillet(0.125)\n",
    "visualize_object(result)\n",
    "\n",
    "result = cq.Workplane(\"XY\").box(3, 3, 0.5).faces(\"+Z\").chamfer(0.1)\n",
    "visualize_object(result)\n",
    "\n",
    "#%% 1.4 Mirorring\n",
    "\n",
    "r = cq.Workplane(\"front\").hLine(1.0)  # 1.0 is the distance, not coordinate\n",
    "\n",
    "r = (\n",
    "    r.vLine(0.5).hLine(-0.25).vLine(-0.25).hLineTo(0.0)\n",
    ")  # hLineTo allows using xCoordinate not distance\n",
    "\n",
    "result = r.mirrorY().extrude(0.25)  # mirror the geometry and extrude\n",
    "visualize_object(result)\n",
    "\n",
    "#%% 2. Boolean Operations\n",
    "\n",
    "# The dimensions of the box. These can be modified rather than changing the\n",
    "# object's code directly.\n",
    "length = 80.0\n",
    "height = 60.0\n",
    "thickness = 10.0\n",
    "center_hole_dia = 22.0\n",
    "\n",
    "# Create a box based on the dimensions above and add a 22mm center hole\n",
    "cube_element = (\n",
    "    cq.Workplane(\"XY\")\n",
    "    .box(length, height, thickness)\n",
    "    .faces(\">Z\")\n",
    "    .workplane()\n",
    "    .hole(center_hole_dia)\n",
    ")\n",
    "\n",
    "#Temp File:\n",
    "result_path = \"../RESULTS/sample_mesh.stl\"\n",
    "\n",
    "# Display the cube with Open3D\n",
    "# Convert the CadQuery solid to a mesh for Open3D compatibility\n",
    "cq.exporters.export(cube_element, result_path)\n",
    "#mesh = cq.mesh(cube_element)\n",
    "\n",
    "# Create an Open3D mesh object from the CadQuery mesh data\n",
    "# open3d_mesh = o3d.geometry.TriangleMesh(mesh.points, mesh.triangles)\n",
    "o3d_mesh = o3d.io.read_triangle_mesh(result_path)\n",
    "o3d_mesh.compute_vertex_normals()\n",
    "\n",
    "# Visualize the mesh with Open3D\n",
    "o3d.visualization.draw_geometries([o3d_mesh])\n",
    "\n",
    "#%%"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def visualize_object(cq_object):\n",
    "    temp_path = \"../RESULTS/temp.stl\"\n",
    "    cq.exporters.export(cq_object, temp_path)\n",
    "    o3d_mesh = o3d.io.read_triangle_mesh(temp_path)\n",
    "    o3d_mesh.compute_vertex_normals()\n",
    "    o3d.visualization.draw_geometries([o3d_mesh])\n",
    "\n",
    "#%% Boolean Opeations Example\n",
    "\n",
    "Box = cq.Workplane(\"XY\").box(1, 1, 1, centered=(False, False, False))\n",
    "Sphere = cq.Workplane(\"XY\").sphere(1)\n",
    "\n",
    "#%% CSG: Intersection\n",
    "result = Box & Sphere\n",
    "visualize_object(result)\n",
    "\n",
    "# CSG: Union\n",
    "result = Box | Sphere\n",
    "visualize_object(result)\n",
    "\n",
    "# CSG: Difference\n",
    "result = Box - Sphere\n",
    "visualize_object(result)\n",
    "\n",
    "#%% Modelling objects:\n",
    "    \n",
    "#%% IPN\n",
    "\n",
    "(L, H, W, t) = (100.0, 20.0, 20.0, 1.0)\n",
    "pts = [\n",
    "    (0, H / 2.0),\n",
    "    (W / 2.0, H / 2.0),\n",
    "    (W / 2.0, (H / 2.0 - t)),\n",
    "    (t / 2.0, (H / 2.0 - t)),\n",
    "    (t / 2.0, (t - H / 2.0)),\n",
    "    (W / 2.0, (t - H / 2.0)),\n",
    "    (W / 2.0, H / -2.0),\n",
    "    (0, H / -2.0),\n",
    "]\n",
    "result = cq.Workplane(\"front\").polyline(pts).mirrorY().extrude(L)\n",
    "visualize_object(result)\n",
    "\n",
    "#%% Spherical joint\n",
    "\n",
    "sphere = cq.Workplane().sphere(5)\n",
    "base = cq.Workplane(origin=(0, 0, -2)).box(12, 12, 10).cut(sphere).edges(\"|Z\").fillet(2)\n",
    "sphere_face = base.faces(\">>X[2] and (not |Z) and (not |Y)\").val()\n",
    "base = base.faces(\"<Z\").workplane().circle(2).extrude(10)\n",
    "\n",
    "shaft = cq.Workplane().sphere(4.5).circle(1.5).extrude(20)\n",
    "\n",
    "spherical_joint = (\n",
    "    base.union(shaft)\n",
    "    .faces(\">X\")\n",
    "    .workplane(centerOption=\"CenterOfMass\")\n",
    "    .move(0, 4)\n",
    "    .slot2D(10, 2, 90)\n",
    "    .cutBlind(sphere_face)\n",
    "    .workplane(offset=10)\n",
    "    .move(0, 2)\n",
    "    .circle(0.9)\n",
    "    .extrude(\"next\")\n",
    ")\n",
    "\n",
    "result = spherical_joint\n",
    "visualize_object(result)\n",
    "\n",
    "#%% Parametric enclosure\n",
    "\n",
    "# parameter definitions\n",
    "p_outerWidth = 100.0  # Outer width of box enclosure\n",
    "p_outerLength = 150.0  # Outer length of box enclosure\n",
    "p_outerHeight = 50.0  # Outer height of box enclosure\n",
    "\n",
    "p_thickness = 3.0  # Thickness of the box walls\n",
    "p_sideRadius = 10.0  # Radius for the curves around the sides of the box\n",
    "p_topAndBottomRadius = (\n",
    "    2.0  # Radius for the curves on the top and bottom edges of the box\n",
    ")\n",
    "\n",
    "p_screwpostInset = 12.0  # How far in from the edges the screw posts should be place.\n",
    "p_screwpostID = 4.0  # Inner Diameter of the screw post holes, should be roughly screw diameter not including threads\n",
    "p_screwpostOD = 10.0  # Outer Diameter of the screw posts.\\nDetermines overall thickness of the posts\n",
    "\n",
    "p_boreDiameter = 8.0  # Diameter of the counterbore hole, if any\n",
    "p_boreDepth = 1.0  # Depth of the counterbore hole, if\n",
    "p_countersinkDiameter = 0.0  # Outer diameter of countersink. Should roughly match the outer diameter of the screw head\n",
    "p_countersinkAngle = 90.0  # Countersink angle (complete angle between opposite sides, not from center to one side)\n",
    "p_flipLid = True  # Whether to place the lid with the top facing down or not.\n",
    "p_lipHeight = 1.0  # Height of lip on the underside of the lid.\\nSits inside the box body for a snug fit.\n",
    "\n",
    "# outer shell\n",
    "oshell = (\n",
    "    cq.Workplane(\"XY\")\n",
    "    .rect(p_outerWidth, p_outerLength)\n",
    "    .extrude(p_outerHeight + p_lipHeight)\n",
    ")\n",
    "\n",
    "# weird geometry happens if we make the fillets in the wrong order\n",
    "if p_sideRadius > p_topAndBottomRadius:\n",
    "    oshell = oshell.edges(\"|Z\").fillet(p_sideRadius)\n",
    "    oshell = oshell.edges(\"#Z\").fillet(p_topAndBottomRadius)\n",
    "else:\n",
    "    oshell = oshell.edges(\"#Z\").fillet(p_topAndBottomRadius)\n",
    "    oshell = oshell.edges(\"|Z\").fillet(p_sideRadius)\n",
    "\n",
    "# inner shell\n",
    "ishell = (\n",
    "    oshell.faces(\"<Z\")\n",
    "    .workplane(p_thickness, True)\n",
    "    .rect((p_outerWidth - 2.0 * p_thickness), (p_outerLength - 2.0 * p_thickness))\n",
    "    .extrude(\n",
    "        (p_outerHeight - 2.0 * p_thickness), False\n",
    "    )  # set combine false to produce just the new boss\n",
    ")\n",
    "ishell = ishell.edges(\"|Z\").fillet(p_sideRadius - p_thickness)\n",
    "\n",
    "# make the box outer box\n",
    "box = oshell.cut(ishell)\n",
    "\n",
    "# make the screw posts\n",
    "POSTWIDTH = p_outerWidth - 2.0 * p_screwpostInset\n",
    "POSTLENGTH = p_outerLength - 2.0 * p_screwpostInset\n",
    "\n",
    "box = (\n",
    "    box.faces(\">Z\")\n",
    "    .workplane(-p_thickness)\n",
    "    .rect(POSTWIDTH, POSTLENGTH, forConstruction=True)\n",
    "    .vertices()\n",
    "    .circle(p_screwpostOD / 2.0)\n",
    "    .circle(p_screwpostID / 2.0)\n",
    "    .extrude(-1.0 * (p_outerHeight + p_lipHeight - p_thickness), True)\n",
    ")\n",
    "\n",
    "# split lid into top and bottom parts\n",
    "(lid, bottom) = (\n",
    "    box.faces(\">Z\")\n",
    "    .workplane(-p_thickness - p_lipHeight)\n",
    "    .split(keepTop=True, keepBottom=True)\n",
    "    .all()\n",
    ")  # splits into two solids\n",
    "\n",
    "# translate the lid, and subtract the bottom from it to produce the lid inset\n",
    "lowerLid = lid.translate((0, 0, -p_lipHeight))\n",
    "cutlip = lowerLid.cut(bottom).translate(\n",
    "    (p_outerWidth + p_thickness, 0, p_thickness - p_outerHeight + p_lipHeight)\n",
    ")\n",
    "\n",
    "# compute centers for screw holes\n",
    "topOfLidCenters = (\n",
    "    cutlip.faces(\">Z\")\n",
    "    .workplane(centerOption=\"CenterOfMass\")\n",
    "    .rect(POSTWIDTH, POSTLENGTH, forConstruction=True)\n",
    "    .vertices()\n",
    ")\n",
    "\n",
    "# add holes of the desired type\n",
    "if p_boreDiameter > 0 and p_boreDepth > 0:\n",
    "    topOfLid = topOfLidCenters.cboreHole(\n",
    "        p_screwpostID, p_boreDiameter, p_boreDepth, 2.0 * p_thickness\n",
    "    )\n",
    "elif p_countersinkDiameter > 0 and p_countersinkAngle > 0:\n",
    "    topOfLid = topOfLidCenters.cskHole(\n",
    "        p_screwpostID, p_countersinkDiameter, p_countersinkAngle, 2.0 * p_thickness\n",
    "    )\n",
    "else:\n",
    "    topOfLid = topOfLidCenters.hole(p_screwpostID, 2.0 * p_thickness)\n",
    "\n",
    "# flip lid upside down if desired\n",
    "if p_flipLid:\n",
    "    topOfLid = topOfLid.rotateAboutCenter((1, 0, 0), 180)\n",
    "\n",
    "# return the combined result\n",
    "result = topOfLid.union(bottom)\n",
    "visualize_object(result)\n",
    "\n",
    "#%% Cycloidal gear\n",
    "\n",
    "import cadquery as cq\n",
    "from math import sin, cos, pi, floor\n",
    "\n",
    "\n",
    "# define the generating function"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def hypocycloid(t, r1, r2):\n",
    "    return (\n",
    "        (r1 - r2) * cos(t) + r2 * cos(r1 / r2 * t - t),\n",
    "        (r1 - r2) * sin(t) + r2 * sin(-(r1 / r2 * t - t)),\n",
    "    )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def epicycloid(t, r1, r2):\n",
    "    return (\n",
    "        (r1 + r2) * cos(t) - r2 * cos(r1 / r2 * t + t),\n",
    "        (r1 + r2) * sin(t) - r2 * sin(r1 / r2 * t + t),\n",
    "    )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def gear(t, r1=4, r2=1):\n",
    "    if (-1) ** (1 + floor(t / 2 / pi * (r1 / r2))) < 0:\n",
    "        return epicycloid(t, r1, r2)\n",
    "    else:\n",
    "        return hypocycloid(t, r1, r2)\n",
    "\n",
    "\n",
    "# create the gear profile and extrude it\n",
    "result = (\n",
    "    cq.Workplane(\"XY\")\n",
    "    .parametricCurve(lambda t: gear(t * 2 * pi, 6, 1))\n",
    "    .twistExtrude(15, 90)\n",
    "    .faces(\">Z\")\n",
    "    .workplane()\n",
    "    .circle(2)\n",
    "    .cutThruAll()\n",
    ")\n",
    "\n",
    "visualize_object(result)\n",
    "\n",
    "#%% Combining Walls\n",
    "\n",
    "# Define parameters (modify these to customize the house)\n",
    "length = 5  # Length of the house in m\n",
    "width = 3  # Width of the house in m\n",
    "height = 2.5  # Height of the house in m\n",
    "\n",
    "wall_thickness = 0.2\n",
    "\n",
    "walls = cq.Workplane(\"XY\").box(length, wall_thickness, height)\n",
    "\n",
    "w1 = walls\n",
    "w2 = walls.translate((0, width, 0))\n",
    "w3 = cq.Workplane(\"XY\").box(width + wall_thickness, wall_thickness, height).rotate((0, 0, 0), (0, 0, 1), 90).translate((length/2, width/2, 0))\n",
    "w4 = cq.Workplane(\"XY\").box(width + wall_thickness, wall_thickness, height).rotate((0, 0, 0), (0, 0, 1), 90).translate((-length/2, width/2, 0))\n",
    "\n",
    "result = w1 | w2 | w3 | w4\n",
    "visualize_object(result)\n",
    "\n",
    "#%% Creating Doors\n",
    "# object = L,W,H,Cx,Cy,Cz,\n",
    "d_par = np.array([1, 0.2, 2])\n",
    "door_relative_shift = np.array([-1, 0, -0.25])\n",
    "\n",
    "d1 = cq.Workplane(\"XY\").box(d_par[0], d_par[1], d_par[2])\n",
    "d1_t = cq.Workplane(\"XY\").box(d_par[0], d_par[1], d_par[2], centered=True).translate((list(door_relative_shift)))\n",
    "\n",
    "visualize_object(d1 | d1_t)\n",
    "\n",
    "result_d = result - d1_t\n",
    "visualize_object(result_d)\n",
    "\n",
    "\n",
    "#%% Generating the ground Ground\n",
    "\n",
    "ground = cq.Workplane(\"XY\").box(length+0.2, width+0.2, 0.1).translate((0,width/2,-height/2-0.1))\n",
    "\n",
    "result_total = result_d | ground\n",
    "visualize_object(result_total)\n",
    "\n",
    "#%%\n",
    "\n",
    "# create 4 small square bumps on a larger base plate:\n",
    "s = (\n",
    "    cq.Workplane()\n",
    "    .box(4, 4, 0.5)\n",
    "    .faces(\">Z\")\n",
    "    .workplane()\n",
    "    .rect(3, 3, forConstruction=True)\n",
    "    .vertices()\n",
    "    .box(0.25, 0.25, 0.25, combine=True)\n",
    ")\n",
    "\n",
    "visualize_object(s)\n",
    "\n",
    "#%%\n",
    "\n",
    "# Define parameters (modify these to customize the house)\n",
    "length = 5  # Length of the house in m\n",
    "width = 3  # Width of the house in m\n",
    "height = 2.5  # Height of the house in m\n",
    "\n",
    "wall_thickness = 0.2\n",
    "\n",
    "door_width = 1  # Width of the door in m\n",
    "door_height = 4  # Height of the door in m\n",
    "window_width = 1.5  # Width of the window in m\n",
    "window_height = 1  # Height of the window in m\n",
    "roof_pitch = 45  # Roof pitch angle in degrees\n",
    "\n",
    "result = cq.Workplane(\"front\").rect(length+wall_thickness, width+wall_thickness).rect(length, width).extrude(height)\n",
    "visualize_object(result)\n",
    "\n",
    "\n",
    "\n",
    "#%%\n",
    "\n",
    "# s = cq.Sketch().rect(door_width, door_height).vertices().fillet(0.02)\n",
    "s = cq.Sketch().rect(door_width, door_height)\n",
    "\n",
    "result2 = (\n",
    "    cq.Workplane(\"front\")\n",
    "    .rect(length+wall_thickness, width+wall_thickness)\n",
    "    .rect(length, width)\n",
    "    .extrude(height)\n",
    "    .faces(\">X\")\n",
    "    .workplane()\n",
    "    #.transformed((0, 0, -90))\n",
    "    .placeSketch(s)\n",
    "    .cutThruAll()\n",
    ")\n",
    "\n",
    "visualize_object(result2)\n",
    "\n",
    "#%%\n",
    "\n",
    "ground = cq.Workplane(\"XY\").box(length+0.2, width+0.2, 0.1)\n",
    "\n",
    "result_total = result2 | ground\n",
    "visualize_object(result_total)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}